sonar.projectKey=mutatos
sonar.projectName=mutatos
sonar.sources=./src
sonar.tests=./tests
sonar.sourceEncoding=UTF-8
sonar.coverageReportPaths=out/genericCoverage.xml
sonar.testExecutionReportPaths=out/genericExecution.xml
